### ISSUE TITLE
The order of the refiled items?

### ISSUE THREAD

**Issue by yoghurtdewdew** [meain/logseq-plugin-refile#2]
Based on the created/updated/completed timestamp? The original order or reverse?

And if the parent block will be refiled as a parent block?

**Comment by meain** [comment]
> Based on the created/updated/completed timestamp? The original order or reverse?

The order is currently based on the order in which items appear in the page.

> And if the parent block will be refiled as a parent block?

For `Refile Completed`, it only pick root level blocks. For `Refile Item` it refiles the entire block and all its children as is.

**Comment by meain** [comment]
I'm closing this issue. Let me know if you have any other thoughts.

**Comment by yoghurtdewdew** [comment]
Thanks for your great work and I think I got it!
