### ISSUE TITLE
Work for journal?

### ISSUE THREAD

**Issue by yoghurtdewdew** [meain/logseq-plugin-refile#3]
I saw the video of using refile in a page.

I wonder if it would work for journals?

**Comment by meain** [comment]
Ahh, it currently has some problems when you have not selected a specific page. I don't think it will be a hard thing to fix, I just haven't looked into it. I'll look into it soon. Just as a FYI, you can click on the date on the journal page to go into the journal page and once you have a specific journal open, this should work.

**Comment by meain** [comment]
The latest version(0.4.0) should also work with journals without having to go to a specific page.

**Comment by yoghurtdewdew** [comment]
Thanks for your great work and it's working now!
