### ISSUE TITLE
ISSUE: "Refile Completed" doesn't work totally

### ISSUE THREAD

**Issue by rd-su** [meain/logseq-plugin-refile#4]
Hi,

Thanks for this useful plugin  :)

I'm using Logseq 0.9.20 with your plugin logseq-plugin-backlog-0.4.0.zip

When I use ```Refile Completed```, for the first time, it just create the page ```<page-name>/Complete```.
Second time it does nothing.

The ```Refile Item``` works fine.

Regards

**Comment by meain** [comment]
Hmm, I'm somehow not able to repro this on my end. Do you see any errors in the JS console? (You can open the console via `ctrl+shift+i`).

I had missed adding it to docs, but only the top level `DONE` and `CANCELLED` items will be refiled. Is this the case for you?

**Comment by rd-su** [comment]
Ok, with the top level tasks works fine.

Thanks
